name: Build & Release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose PyPI environment'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - production
  push:

jobs:
  build:
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version || '3.11' }}

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build dists
        run: |
          python -m build

      - name: Upload dists artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Download dists artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to TestPyPI
        if: inputs.environment == 'test'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to Production PyPI
        if: inputs.environment == 'production'
        uses: pypa/gh-action-pypi-publish@release/v1