name: Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: Python version to use for building
        required: false
        default: "3.11"
      skip_existing:
        description: Skip uploading files that already exist on TestPyPI
        required: false
        default: "true"
  push:
    tags:
      - "test-v*"

jobs:
  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version || '3.11' }}

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build dists
        run: |
          python -m build

      - name: Upload dists artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    name: Publish to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dists artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/